# Generated by Django 6.0.1 on 2026-01-31 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(blank=True, max_length=20, unique=True)),
                ('nama_produk', models.CharField(max_length=150)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.IntegerField(default=0)),
                ('stok_minimum', models.IntegerField(default=5)),
                ('satuan', models.CharField(default='pcs', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produk', to='kategori.kategori')),
            ],
        ),
    ]
