# Generated by Django 6.0.1 on 2026-07-01 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatHarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_beli_lama', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_beli_baru', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_jual_lama', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_jual_baru', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diubah_pada', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_harga', to='produk.produk')),
            ],
            options={
                'verbose_name': 'Riwayat Harga',
                'verbose_name_plural': 'Riwayat Harga',
                'ordering': ['-diubah_pada'],
            },
        ),
    ]
