# Generated by Django 6.0.1 on 2026-07-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_riwayatharga'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='garansi_hari',
            field=models.PositiveIntegerField(default=0, help_text='Lama garansi toko dalam hari. Isi 0 kalau produk ini tidak ada garansi.'),
        ),
        migrations.AddField(
            model_name='produk',
            name='kondisi',
            field=models.CharField(choices=[('baru', 'Baru'), ('second', 'Second'), ('refurbished', 'Refurbished')], default='baru', max_length=15),
        ),
    ]
