# Generated by Django 6.0.1 on 2026-04-20 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoToko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(default='Toko Saya', max_length=150)),
                ('alamat', models.TextField(blank=True)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('stok_minimum_default', models.IntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info Toko',
            },
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('tambah', 'Tambah Data'), ('ubah', 'Ubah Data'), ('hapus', 'Hapus / Nonaktifkan')], max_length=20)),
                ('keterangan', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_aktivitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'ordering': ['-waktu'],
            },
        ),
    ]
