# Generated by Django 6.0.1 on 2026-01-31 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perubahan', models.IntegerField()),
                ('stok_sebelum', models.IntegerField()),
                ('stok_sesudah', models.IntegerField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_stok', to='produk.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('jenis_transaksi', models.CharField(choices=[('MASUK', 'Barang Masuk'), ('KELUAR', 'Barang Keluar')], max_length=10)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produk.produk')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='transaksi.transaksi')),
            ],
        ),
    ]
