# Generated by Django 6.0.1 on 2026-07-01 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_riwayatharga'),
        ('supplier', '0001_initial'),
        ('transaksi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi', to='supplier.supplier'),
        ),
        migrations.CreateModel(
            name='StokOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_sistem', models.IntegerField()),
                ('stok_fisik', models.IntegerField()),
                ('selisih', models.IntegerField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_opname', to='produk.produk')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_opname', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stok Opname',
                'verbose_name_plural': 'Stok Opname',
                'ordering': ['-tanggal'],
            },
        ),
    ]
